### ISSUE TITLE
emoji显示为方块

### ISSUE THREAD

**Issue by lgdsgd2000** [flathub/com.tencent.WeChat#1]
从[web1n的仓库](https://github.com/web1n/wechat-universal-flatpak/releases)下载的就不会

**Comment by jcleng** [comment]
需要增加emoji字体
https://github.com/web1n/wechat-universal-flatpak/blob/a5b82eee3535cc1e3048e5fbf2876dddea4bccec/com.tencent.WeChat.yaml#L75
