### ISSUE TITLE
无法从flathub下载安装

### ISSUE THREAD

**Issue by aaasoft** [flathub/com.tencent.WeChat#10]
是不是麒麟的源不可用了？是不是可以换成UOS的源。
安装的时候提示如下内容：

flatpak install com.tencent.WeChat
寻找匹配项…

com.tencent.WeChat permissions:
    ipc          network              pulseaudio           x11
    devices      file access [1]      dbus access [2]      bus ownership [3]

    [1] xdg-download
    [2] org.freedesktop.FileManager1, org.freedesktop.Notifications,
        org.kde.StatusNotifierWatcher
    [3] org.kde.*

        ID                    分支      操作    远程       下载
 1. [✗] com.tencent.WeChat    stable    i       flathub    1.0 kB / 117.4 MB

Error: 下载 https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb 时：While fetching https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb: [56] Failure when receiving data from the peer
错误： Failed to install com.tencent.WeChat: 下载 https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb 时：While fetching https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb: [56] Failure when receiving data from the peer

**Comment by zhsj** [comment]
你直接访问这个链接也会报错吗？命令行输入 `curl -v -o /dev/null 'https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb'` 看看报什么错，结果贴在issue里看一下。

**Comment by aaasoft** [comment]
> 你直接访问这个链接也会报错吗？命令行输入 `curl -v -o /dev/null 'https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb'` 看看报什么错，结果贴在issue里看一下。

现在测试可以了，flatpak命令也可以安装了，可能是上次麒麟的服务器不稳定，那天试了好多次都不行。

结果如下：
curl -v -o /dev/null 'https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host archive2.kylinos.cn:443 was resolved.
* IPv6: (none)
* IPv4: 36.147.63.75
*   Trying 36.147.63.75:443...
* Connected to archive2.kylinos.cn (36.147.63.75) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [112 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3885 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / X25519 / RSASSA-PSS
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=CN; ST=\U5929\U6D25\U5E02; O=\U9E92\U9E9F\U8F6F\U4EF6\U6709\U9650\U516C\U53F8; CN=*.kylinos.cn
*  start date: Feb  6 00:00:00 2024 GMT
*  expire date: Feb  5 23:59:59 2025 GMT
*  subjectAltName: host "archive2.kylinos.cn" matched cert's "*.kylinos.cn"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Secure Site CN CA G3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
* using HTTP/1.x
} [5 bytes data]
> GET /deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb HTTP/1.1
> Host: archive2.kylinos.cn
> User-Agent: curl/8.5.0
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Last-Modified: Fri, 15 Mar 2024 06:25:35 GMT
< Etag: "6f5bacc-613ad13590c5a"
< Date: Thu, 18 Apr 2024 12:15:36 GMT
< Server: Apache
< Content-Type: application/octet-stream
< Content-Length: 116767436
< Accept-Ranges: bytes
< X-NWS-LOG-UUID: 5106301226243882030
< Connection: keep-alive
< X-Cache-Lookup: Cache Hit
< 
{ [5 bytes data]
100  111M  100  111M    0     0  14.7M      0  0:00:07  0:00:07 --:--:-- 15.5M
* Connection #0 to host archive2.kylinos.cn left intact

**Comment by aaasoft** [comment]
今天再次出现这个问题了。我用wget下载也是出错。下面是错误日志。

wget https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
--2024-07-14 23:24:07--  https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
正在解析主机 archive2.kylinos.cn (archive2.kylinos.cn)... 183.237.146.115, 112.48.244.136
正在连接 archive2.kylinos.cn (archive2.kylinos.cn)|183.237.146.115|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 116767436 (111M) [application/octet-stream]
正在保存至: ‘wechat-beta_1.0.0.238_amd64.deb’

wechat-beta_1.0.0.2   0%[                    ]   1016K  3.11MB/s    用时 0.3s  

2024-07-14 23:24:08 (3.11 MB/s) - 在 1040384/116767436 字节处发生读取错误 (连接被对方重置)。 重试中。

--2024-07-14 23:24:09--  (尝试次数： 2)  https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
正在连接 archive2.kylinos.cn (archive2.kylinos.cn)|183.237.146.115|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度： 116767436 (111M)，剩余 115727052 (110M) [application/octet-stream]
正在保存至: ‘wechat-beta_1.0.0.238_amd64.deb’

wechat-beta_1.0.0.2   0%[                    ]   1016K  --.-KB/s    用时 0s    

2024-07-14 23:24:09 (0.00 B/s) - 在 1040384/116767436 字节处发生读取错误 (连接被对方重置)。 重试中。

--2024-07-14 23:24:11--  (尝试次数： 3)  https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
正在连接 archive2.kylinos.cn (archive2.kylinos.cn)|183.237.146.115|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度： 116767436 (111M)，剩余 115727052 (110M) [application/octet-stream]
正在保存至: ‘wechat-beta_1.0.0.238_amd64.deb’

wechat-beta_1.0.0.2   0%[                    ]   1016K  --.-KB/s    用时 0s    

2024-07-14 23:24:11 (0.00 B/s) - 在 1040384/116767436 字节处发生读取错误 (连接被对方重置)。 重试中。

--2024-07-14 23:24:14--  (尝试次数： 4)  https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
正在连接 archive2.kylinos.cn (archive2.kylinos.cn)|183.237.146.115|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度： 116767436 (111M)，剩余 115727052 (110M) [application/octet-stream]
正在保存至: ‘wechat-beta_1.0.0.238_amd64.deb’

wechat-beta_1.0.0.2   0%[                    ]   1016K  --.-KB/s    用时 0s    

2024-07-14 23:24:15 (0.00 B/s) - 在 1040384/116767436 字节处发生读取错误 (连接被对方重置)。 重试中。

--2024-07-14 23:24:19--  (尝试次数： 5)  https://archive2.kylinos.cn/deb/kylin/production/PART-openKylin/custom/partner/openKylin/pool/all/wechat-beta_1.0.0.238_amd64.deb
正在连接 archive2.kylinos.cn (archive2.kylinos.cn)|183.237.146.115|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度： 116767436 (111M)，剩余 115727052 (110M) [application/octet-stream]
正在保存至: ‘wechat-beta_1.0.0.238_amd64.deb’

wechat-beta_1.0.0.2   0%[                    ]   1016K  --.-KB/s    用时 0s    

2024-07-14 23:24:19 (0.00 B/s) - 在 1040384/116767436 字节处发生读取错误 (连接被对方重置)。 重试中。

**Comment by zhsj** [comment]
把下载地址切换到了 https://software.openkylin.top/ 这个地址是 openkylin 安装后实际使用的，可能会更稳定。

**Comment by aaasoft** [comment]
> 把下载地址切换到了 https://software.openkylin.top/ 这个地址是 openkylin 安装后实际使用的，可能会更稳定（虽然两个地址都是腾讯云的 CDN）。

换地址后，现在可以下载了，感谢。
