### ISSUE TITLE
任务栏无法显示图标

### ISSUE THREAD

**Issue by hh-Ink** [flathub/com.tencent.WeChat#15]
任务栏无法显示图标

系统版本：
![image](https://github.com/user-attachments/assets/da23788d-2a29-4053-918b-fb544b6ed624)

表现：

![image](https://github.com/user-attachments/assets/161011ab-a0bb-40e6-bebe-1691a61c2d9b)

**Comment by zhsj** [comment]
其他flathub上的程序能显示吗？

**Comment by hh-Ink** [comment]
flathub上的网易云音乐可以正常显示
