### ISSUE TITLE
文件浏览器只能看到“下载”文件夹，没有“桌面”文件夹

### ISSUE THREAD

**Issue by Mr-Spade** [flathub/com.tencent.WeChat#16]
如题，在聊天框内点击文件夹图标选择文件，文件浏览器内只能进入“下载”文件夹，无法看到“桌面”、“文档”等其它位于主文件夹下的文件夹。

如能拔冗解决这一问题，将十分感谢！

**Comment by zhsj** [comment]
可以安装[flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)，然后把对应目录的权限给微信加上。
