### ISSUE TITLE
Linux Mint 22 下微信来新通知会异常退出

### ISSUE THREAD

**Issue by mangege** [flathub/com.tencent.WeChat#17]
原因有可能是 Linux Mint 22 音频从 PulseAudio 切换 Pipewire , 而微信 Linux 不支持  Pipewire.

临时解决办法有两个: 
1. 改回 PulseAudio ,参考链接 https://www.linuxmint.com/rel_wilma.php.
2. 关闭微信的通知声音.

看看能不能确认是 Pipewire 的问题,且能支持 Pipewire .

**Comment by zhsj** [comment]
这个和flatpak无关吧。。。 假设微信真不支持Pipewire，这里也解决不了。这个仓库和微信官方无关，只维护flatpak打包的脚本。
