### ISSUE TITLE
聊天记录无法和手机或者windows同步&&& 根据手机号码或者账号添加新的联系人。

### ISSUE THREAD

**Issue by bbzzhh1** [flathub/com.tencent.WeChat#19]
如题，
如何才能做到把手机的聊天记录或者windows上的聊天记录迁移到linux-wechat上。
如果

添加联系人功能

**Comment by zhsj** [comment]
应该做不到。

你可以通过微信内的“意见反馈”反馈给微信官方。本仓库只是flatpak打包脚本，与微信官方无关。

![image](https://github.com/user-attachments/assets/8f220dca-9ddc-4fc5-8337-00e2241e0890)
