### ISSUE TITLE
任务栏只有“退出微信”的选项，请问可以加上“显示窗口”吗

### ISSUE THREAD

**Issue by TRSWNCA** [flathub/com.tencent.WeChat#24]
![image](https://github.com/user-attachments/assets/7d4fbdf7-c311-4a5e-829c-42d7c63c554a)

环境是 Gnome-shell。现在如果需要把它打开需要多次双击任务栏中的图标，如果加上“显示窗口”的选项就挺好，谢谢。

**Comment by zhsj** [comment]
非flatpak相关问题。

另外可以参考 https://github.com/web1n/wechat-universal-flatpak/issues/19#issuecomment-2004180183
