### ISSUE TITLE
4.0.0.21之后就不能登录了？

### ISSUE THREAD

**Issue by nessusing** [flathub/com.tencent.WeChat#37]
Mint22。看commit history，应该是Drop redirect patch之后就不能在桌面登录了。rollback到之前的commit就还可以。
最新的4.0.0.30也不行。

**Comment by nessusing** [comment]
nvm，直接安装了官方deb包也还是不能登录。

**Comment by kands-code** [comment]
ArchLinux, 同样在更新后就无法登录，显示安全验证未通过，但是 [`aur/wechat`](https://aur.archlinux.org/packages/wechat) 可以正常登录

**Comment by Erven2016** [comment]
我有两个账号，一个外区账号，一个国区账号，比较难绷的是国区账号可以正常登陆，外区账号直接提示登陆失败。
![Screenshot from 2024-11-06 00-14-04](https://github.com/user-attachments/assets/aca1b73c-6706-42f0-9a29-2a2dcb5280d0)

**Comment by junjieyuan** [comment]
ea89fde32d96e2e54046346408cef82ac91787f4 能正常使用，我是从 35d7c0bdf9b2f39c5cea3f1d957b045ed5b6de73 一路升级的，都可以正常使用。

---

# Software Information:
- **OS Name:**                                     Fedora Linux 41.20241107.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.6-300.fc41.x86_64
- **Flatpak Version                                1.15.10

**Comment by nessusing** [comment]
4.0.0.21 and 30用的都是微信官方deb版。看来可以证实外区（海外）用户是无法用官方版登录的。和登录web版一个症状。

**Comment by zhsj** [comment]
不是 flatpak 的问题。

https://github.com/flathub/com.tencent.WeChat/pull/30#issuecomment-2456670325

如果需要回退1.0版本，可以使用

```
flatpak update --commit=f097c4fea55b096b6f1b1c096e8f24c149d6ea1ea909eb1fb2bf179fe37a16f8 com.tencent.WeChat
```

https://linux.weixin.qq.com/ 上有个交流群可以去反馈：

> 微信Linux版官方QQ交流群：736511883

**Comment by nessusing** [comment]
谁有QQ的希望能在官方交流群里询问一下。我是海外用户，QQ现在也注册不上。老号早就作废了。。。

**Comment by zhsj** [comment]
另外注意到这里的评论，https://aur.archlinux.org/packages/wechat-universal-bwrap#comment-997499 可以试一下把 https://aur.archlinux.org/cgit/aur.git/tree/libuosdevicea.c?h=wechat-universal-bwrap 加进去，本地构建一个版本。

**Comment by zhsj** [comment]
archwiki 有人加了个提示 https://wiki.archlinuxcn.org/wiki/%E5%BE%AE%E4%BF%A1#Linux_%E7%89%88

![image](https://github.com/user-attachments/assets/4ac45866-ec40-41d4-be08-df7e967e241b)

**Comment by kands-code** [comment]
> archwiki 有人加了个提示 https://wiki.archlinuxcn.org/wiki/%E5%BE%AE%E4%BF%A1#Linux_%E7%89%88
> 
> ![image](https://github.com/user-attachments/assets/4ac45866-ec40-41d4-be08-df7e967e241b)

我并非海外用户，也开通了支付功能，但是目前对于 WeChat Linux 4.0 的版本，我目前只有 aur/wechat 可以正常使用，连官网版本的 deb 和 appimage 都不能正常登录，目测目前版本还是有一些检测，可能是对于网络环境检测，也可能是 Linux 发行版检测

**Comment by Erven2016** [comment]
> > archwiki 有人加了个提示 https://wiki.archlinuxcn.org/wiki/%E5%BE%AE%E4%BF%A1#Linux_%E7%89%88
> > ![image](https://private-user-images.githubusercontent.com/227180/384156816-4ac45866-ec40-41d4-be08-df7e967e241b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTYxNzAsIm5iZiI6MTczMTA1NTg3MCwicGF0aCI6Ii8yMjcxODAvMzg0MTU2ODE2LTRhYzQ1ODY2LWVjNDAtNDFkNC1iZTA4LWRmN2U5NjdlMjQxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwODUxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWU1MWM2OTljMjVlZTA2MThlYzZiNTYyODczMTZkNGNhOTY3YWJmNzM2ZTBhMjQ2MDllNWFkZjFjNWRhYWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rYSnM5um8PyS9yyCvwK58edkdlram9-SI6hQwQ60of8)
> 
> 我并非海外用户，也开通了支付功能，但是目前对于 WeChat Linux 4.0 的版本，我目前只有 aur/wechat 可以正常使用，连官网版本的 deb 和 appimage 都不能正常登录，目测目前版本还是有一些检测，可能是对于网络环境检测，也可能是 Linux 发行版检测

 现在可以试试了，我几分钟前试了海外账号可以正常登陆，这应该是微信服务器那边接口的限制？

**Comment by kands-code** [comment]
确实，我也登上了，看来大概是微信解除限制了

**Comment by Erven2016** [comment]
海外账户又不给登陆了（2024-12-15），还有登陆状态的友友别退出登陆了 :sweat_smile:
