### ISSUE TITLE
4.0.0.30 版本字体显示有问题

### ISSUE THREAD

**Issue by kands-code** [flathub/com.tencent.WeChat#38]
如题，具体问题显示如下图：
![image](https://github.com/user-attachments/assets/0338eaae-32cb-4078-bbd4-86f07a4eee1c)

感觉微信并没有读取或者使用到全局的 fontconfig 设置，但是自己内置字体的 fallback 顺序又有问题

**Comment by zhsj** [comment]
非flatpak问题请向微信官方反馈

https://linux.weixin.qq.com/

> 微信Linux版官方QQ交流群：736511883

**Comment by kands-code** [comment]
我就是没有通过入群申请所以才来这里问问的，看看有没有什么解决方法
