### ISSUE TITLE
更新到KDE6后fcitx-rime无法使用

### ISSUE THREAD

**Issue by Icarus-Xu** [flathub/com.tencent.WeChat#42]
OS: Debian GNU/Linux trixie/sid x86_64
Host: HP ProDesk 680 G4 MT 
Kernel: 6.11.10-amd64 
Shell: zsh 5.9 
DE: Plasma 6.2.3 
WM: kwin
Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: konsole

Name                              Application ID                     Version                  Branch      Installation
WeChat                            com.tencent.WeChat                 4.0.0.30                 stable      system
Piper                             org.freedesktop.Piper              0.8                      stable      system
Freedesktop Platform              org.freedesktop.Platform           freedesktop-sdk-23.08.25 23.08       system
Freedesktop Platform              org.freedesktop.Platform           freedesktop-sdk-24.08.7  24.08       system
Mesa                              …g.freedesktop.Platform.GL.default 24.2.5                   23.08       system
Mesa (Extra)                      …g.freedesktop.Platform.GL.default 24.2.5                   23.08-extra system
Mesa                              …g.freedesktop.Platform.GL.default 24.2.7                   24.08       system
Mesa (Extra)                      …g.freedesktop.Platform.GL.default 24.2.7                   24.08extra  system
Intel VAAPI driver                ….freedesktop.Platform.VAAPI.Intel                          23.08       system
Intel VAAPI driver                ….freedesktop.Platform.VAAPI.Intel                          24.08       system
FFmpeg extension with extra code… ….freedesktop.Platform.ffmpeg-full                          24.08       system
openh264                          org.freedesktop.Platform.openh264  2.1.0                    2.2.0       system
openh264                          org.freedesktop.Platform.openh264  2.4.1                    2.4.1       system
GNOME Application Platform versi… org.gnome.Platform                                          46          system
GNOME Application Platform versi… org.gnome.Platform                                          47          system
Breeze GTK theme                  org.gtk.Gtk3theme.Breeze           6.2.4                    3.22        system
KDE Application Platform          org.kde.Platform                                            6.7         system
KDE Application Platform          org.kde.Platform                                            6.8         system
LibreOffice                       org.libreoffice.LibreOffice        24.8.3.2                 stable      system

libreoffice可以使用fcitx-rime

**Comment by zhsj** [comment]
Debian里的 fcitx-rime 是 fcitx4，请更新到 fcitx5-rime。

**Comment by Icarus-Xu** [comment]
@zhsj 抱歉刚刚看到回复，我使用的是debian sid，安装的是fcitx5-rime

➜  ~ sudo apt search fcitx5-rime
fcitx5-rime/testing,now 5.1.9-2 amd64 [installed]
  Rime input method support for fcitx5

微信版本4.0.1.11中，小程序内可以使用rime输入法，主程序不行

**Comment by zhsj** [comment]
我也是用debian和kde6，没有问题的。

你运行下fcitx5-diagnose，结果贴一下。

**Comment by Icarus-Xu** [comment]
[diagnose.txt](https://github.com/user-attachments/files/18331886/diagnose.txt)

感谢回复，贴到附件了

**Comment by zhsj** [comment]
```
          IC [51bb710366b14fe88cabbba6fbf7d30f] program:wechat frontend:wayland cap:72 focus:0
```

应该是这里的问题，微信内置的Qt好像不支持wayland协议。正常情况下，我系统上wechat用的是dbus前端：

```
  IC [8ad5f5467ab94291aa12c7bcb04f37ec] program:wechat frontend:dbus cap:800072 focus:0
```

问题应该是你没有设置XMODIFIERS环境变量，日志里有

```
## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

```

原因是wechat的启动命令里有根据 XMODIFIERS 环境变量设置其他输入法相关环境变量的代码：

https://github.com/flathub/com.tencent.WeChat/blob/9e0cf7a6a521ed9fde669e7ae5a47e42ba9ece07/wechat.sh#L3-L11

可以参考 https://fcitx-im.org/wiki/Setup_Fcitx_5#Environment_variables 设置环境变量

**Comment by Icarus-Xu** [comment]
好的，非常感谢，我试一试，麻烦了

**Comment by Icarus-Xu** [comment]
更新下结果：

正如 @zhsj 所说，此问题应该是微信默认不支持wayland协议引起，我在没有配置任何环境变量的状态切换到x11，输入法可以正常使用，查看kde6 release note发现[kde6将sddm默认改成wayland](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2188)，我猜测可能是我没有修改过kde5的默认配置所以升级前用的是x11，升级后用的是wayland。

参考文档中对plasma的描述`A env script location that only works for Plasma desktop, you need to create your own .sh file, e.g. ~/.config/plasma-workspace/env/im.sh and put the code snippet same as login shell.`修改后，输入法可以正常使用

感谢 @zhsj 的帮助
